Makefile etc/init.d/neubot: use new startup procedure

diff --git a/etc/init.d/neubot b/etc/init.d/neubot
--- a/etc/init.d/neubot
+++ b/etc/init.d/neubot
@@ -20,19 +20,25 @@
 
 case $1 in
     "start")
-        if ps aux|grep /usr/bin/neubot|grep -v grep 1>/dev/null; then
-            echo "error: neubot seems to be already running."
-            exit 1
+        if [ -f /var/run/neubot.pid ]; then
+            PID=`cat /var/run/neubot.pid`
+            if kill -0 $PID; then
+                echo "error: neubot already running with pid $PID."
+                exit 1
+            fi
         fi
-        echo "Starting neubot: /usr/bin/neubot"
-        /usr/bin/neubot
+        echo "Starting neubot: /usr/bin/neubot -b"
+        /usr/bin/neubot -b
         ;;
     "stop")
-        PIDLIST=`ps aux|grep /usr/bin/neubot|grep -v grep|awk '{print $2}'`
-        echo "Stopping neubot"
-        for PID in $PIDLIST; do
-            kill -QUIT $PID
-        done
+        if [ -f /var/run/neubot.pid ]; then
+            PID=`cat /var/run/neubot.pid`
+            if kill -0 $PID; then
+                echo "Stopping neubot: kill -QUIT $PID"
+                kill -QUIT $PID
+            fi
+            rm -rf /var/run/neubot.pid
+        fi
         ;;
     "restart")
         /etc/init.d/neubot stop
